/** @type {import('tailwindcss').Config} */
export default {
  darkMode: ["class", '[data-theme*="dark"]'],
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "outline-variant": "var(--outline-variant)",
        "on-secondary-fixed": "var(--on-secondary-fixed)",
        "on-surface-variant": "var(--on-surface-variant)",
        "on-secondary-container": "var(--on-secondary-container)",
        "on-primary-container": "var(--on-primary-container)",
        "primary-fixed-dim": "var(--primary-fixed-dim)",
        "error": "var(--error)",
        "secondary-fixed": "var(--secondary-fixed)",
        "primary-container": "var(--primary-container)",
        "secondary-container": "var(--secondary-container)",
        "surface-bright": "var(--surface-bright)",
        "surface-container-low": "var(--surface-container-low)",
        "tertiary-fixed": "var(--tertiary-fixed)",
        "on-error": "var(--on-error)",
        "on-primary-fixed-variant": "var(--on-primary-fixed-variant)",
        "surface-container-high": "var(--surface-container-high)",
        "secondary-fixed-dim": "var(--secondary-fixed-dim)",
        "surface-container-lowest": "var(--surface-container-lowest)",
        "inverse-on-surface": "var(--inverse-on-surface)",
        "background": "var(--bg-background)",
        "surface-container": "var(--surface-container)",
        "tertiary-container": "var(--tertiary-container)",
        "surface-variant": "var(--surface-variant)",
        "surface": "var(--surface)",
        "on-tertiary-container": "var(--on-tertiary-container)",
        "outline": "var(--outline)",
        "on-primary-fixed": "var(--on-primary-fixed)",
        "on-background": "var(--on-background)",
        "on-tertiary-fixed": "var(--on-tertiary-fixed)",
        "inverse-primary": "var(--inverse-primary)",
        "on-primary": "var(--on-primary)",
        "surface-tint": "var(--surface-tint)",
        "secondary": "var(--secondary)",
        "error-container": "var(--error-container)",
        "on-tertiary": "var(--on-tertiary)",
        "surface-dim": "var(--surface-dim)",
        "surface-container-highest": "var(--surface-container-highest)",
        "on-secondary": "var(--on-secondary)",
        "on-error-container": "var(--on-error-container)",
        "primary": "var(--primary)",
        "tertiary-fixed-dim": "var(--tertiary-fixed-dim)",
        "tertiary": "var(--tertiary)",
        "on-surface": "var(--on-surface)",
        "primary-fixed": "var(--primary-fixed)",
        "on-secondary-fixed-variant": "var(--on-secondary-fixed-variant)",
        "on-tertiary-fixed-variant": "var(--on-tertiary-fixed-variant)",
        "inverse-surface": "var(--inverse-surface)",
        card: {
          DEFAULT: "var(--surface-container-lowest)",
          foreground: "var(--on-surface)",
        },
        muted: {
          DEFAULT: "var(--surface-container-low)",
          foreground: "var(--on-surface-variant)",
        },
      },
      spacing: {
        "gutter": "1.5rem",
        "space-xs": "0.25rem",
        "space-sm": "0.5rem",
        "space-md": "1rem",
        "space-lg": "1.5rem",
        "space-xl": "2.5rem",
        "margin": "2rem",
        "gutter-mobile": "0.75rem",
        "margin-mobile": "1rem",
      },
      fontFamily: {
        sans: ["Inter", "-apple-system", "BlinkMacSystemFont", "sans-serif"],
        heading: ["Geist", "sans-serif"],
        "headline-lg": ["Geist", "sans-serif"],
        "label-lg": ["Geist", "sans-serif"],
        "label-md": ["Geist", "sans-serif"],
        "tabular-data": ["Geist", "monospace"],
        "headline-xl": ["Geist", "sans-serif"],
        "label-sm": ["Geist", "sans-serif"],
        "body-sm": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "headline-xl-mobile": ["Geist", "sans-serif"],
        "display-lg": ["Geist", "sans-serif"],
        "headline-sm": ["Geist", "sans-serif"],
        "metric-display": ["Geist", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "headline-md": ["Geist", "sans-serif"],
        "display-lg-mobile": ["Geist", "sans-serif"],
      },
      fontSize: {
        "headline-lg": ["24px", { lineHeight: "32px", letterSpacing: "-0.015em", fontWeight: "600" }],
        "label-lg": ["14px", { lineHeight: "20px", letterSpacing: "-0.005em", fontWeight: "500" }],
        "label-md": ["12px", { lineHeight: "16px", letterSpacing: "0.01em", fontWeight: "500" }],
        "tabular-data": ["13px", { lineHeight: "18px", letterSpacing: "-0.005em", fontWeight: "500" }],
        "headline-xl": ["32px", { lineHeight: "40px", letterSpacing: "-0.02em", fontWeight: "600" }],
        "label-sm": ["11px", { lineHeight: "14px", letterSpacing: "0.04em", fontWeight: "600" }],
        "body-sm": ["12px", { lineHeight: "18px", letterSpacing: "0.005em", fontWeight: "400" }],
        "body-lg": ["16px", { lineHeight: "26px", letterSpacing: "-0.005em", fontWeight: "400" }],
        "headline-xl-mobile": ["26px", { lineHeight: "34px", letterSpacing: "-0.015em", fontWeight: "600" }],
        "display-lg": ["44px", { lineHeight: "52px", letterSpacing: "-0.025em", fontWeight: "600" }],
        "headline-sm": ["16px", { lineHeight: "24px", letterSpacing: "-0.005em", fontWeight: "600" }],
        "metric-display": ["36px", { lineHeight: "40px", letterSpacing: "-0.03em", fontWeight: "600" }],
        "body-md": ["14px", { lineHeight: "22px", letterSpacing: "0em", fontWeight: "400" }],
        "headline-md": ["20px", { lineHeight: "28px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "display-lg-mobile": ["32px", { lineHeight: "40px", letterSpacing: "-0.02em", fontWeight: "600" }],
      },
    },
  },
  plugins: [],
}
