import {
  Student,
  Course,
  TimetableSlot,
  Assignment,
  FeeItem,
  PlacementDrive,
  DSACategory,
  AIStudyTask,
} from '../types';
import { calculateAttendance } from './attendanceEngine';

export const mockStudentProfile: Student = {
  name: "Pragyan Jain",
  regNo: "24BLC1100",
  email: "24blc1100@vitstudent.ac.in",
  program: "B.Tech - Electronics and Communication Engineering",
  branch: "School of Electronics Engineering (SENSE)",
  semester: 5,
  batch: "2024 - 2028",
  cgpa: 8.85,
  creditsEarned: 68,
  totalCreditsRequired: 160,
  rank: 8,
  lastSynced: "Just now (VTOP Active Session)",
  overallAttendance: calculateAttendance(108, 123),
  semesterGpa: [
    { semester: 1, gpa: 8.75, cgpa: 8.75, credits: 21 },
    { semester: 2, gpa: 8.90, cgpa: 8.82, credits: 22 },
    { semester: 3, gpa: 8.80, cgpa: 8.81, credits: 23 },
    { semester: 4, gpa: 8.92, cgpa: 8.85, credits: 22 },
  ],
};

export const mockCourses: Course[] = [
  {
    id: "bece355l",
    code: "BECE355L",
    title: "Advanced Cloud Computing",
    type: "Theory",
    slot: "C1 + TC1",
    venue: "AB-2 • Room 402",
    room: { roomNumber: "402", blockName: "Academic Block 2", fullVenue: "AB-2 • Room 402" },
    faculty: "Dr. Prabhakar V",
    credits: 3,
    attendance: calculateAttendance(17, 20),
    marks: {
      cat1: { scored: 45, max: 50, weightage: 15 },
      cat2: { scored: 46, max: 50, weightage: 15 },
      da1: { scored: 10, max: 10, weightage: 10 },
      da2: { scored: 9.5, max: 10, weightage: 10 },
      quiz: { scored: 10, max: 10, weightage: 10 },
      fatProjected: { minNeededForS: 75, minNeededForA: 60, max: 100 },
    },
  },
  {
    id: "bcse308l",
    code: "BCSE308L",
    title: "Computer Networks & Protocols",
    type: "Embedded",
    slot: "D1 + TD1",
    venue: "AB-3 • Room 208",
    room: { roomNumber: "208", blockName: "Academic Block 3", fullVenue: "AB-3 • Room 208" },
    faculty: "Prof. Shalini Roy",
    credits: 4,
    attendance: calculateAttendance(21, 24),
    marks: {
      cat1: { scored: 47, max: 50, weightage: 15 },
      cat2: { scored: 48, max: 50, weightage: 15 },
      da1: { scored: 10, max: 10, weightage: 10 },
      da2: { scored: 10, max: 10, weightage: 10 },
      quiz: { scored: 9.5, max: 10, weightage: 10 },
      fatProjected: { minNeededForS: 70, minNeededForA: 55, max: 100 },
    },
  },
  {
    id: "bece309l",
    code: "BECE309L",
    title: "Artificial Intelligence & Machine Learning",
    type: "Theory",
    slot: "B1 + TB1",
    venue: "SJT • Room 504",
    room: { roomNumber: "504", blockName: "Silver Jubilee Tower", fullVenue: "SJT • Room 504" },
    faculty: "Dr. K. S. Ramanujam",
    credits: 4,
    attendance: calculateAttendance(19, 22),
    marks: {
      cat1: { scored: 42, max: 50, weightage: 15 },
      cat2: { scored: 44, max: 50, weightage: 15 },
      da1: { scored: 9, max: 10, weightage: 10 },
      da2: { scored: 9, max: 10, weightage: 10 },
      quiz: { scored: 9, max: 10, weightage: 10 },
      fatProjected: { minNeededForS: 80, minNeededForA: 65, max: 100 },
    },
  },
  {
    id: "bcse302l",
    code: "BCSE302L",
    title: "Database Systems & Architecture",
    type: "Theory",
    slot: "A1 + TA1",
    venue: "AB-2 • Room 304",
    room: { roomNumber: "304", blockName: "Academic Block 2", fullVenue: "AB-2 • Room 304" },
    faculty: "Dr. Rajesh Varma",
    credits: 4,
    attendance: calculateAttendance(18, 21),
    marks: {
      cat1: { scored: 44, max: 50, weightage: 15 },
      cat2: { scored: 46, max: 50, weightage: 15 },
      da1: { scored: 10, max: 10, weightage: 10 },
      da2: { scored: 9.5, max: 10, weightage: 10 },
      quiz: { scored: 10, max: 10, weightage: 10 },
      fatProjected: { minNeededForS: 78, minNeededForA: 64, max: 100 },
    },
  },
  {
    id: "bmat202l",
    code: "BMAT202L",
    title: "Probability and Statistics",
    type: "Theory",
    slot: "E1 + TE1",
    venue: "MB • Room 118",
    room: { roomNumber: "118", blockName: "Main Building", fullVenue: "MB • Room 118" },
    faculty: "Dr. Thangaraj M",
    credits: 4,
    attendance: calculateAttendance(20, 22),
    marks: {
      cat1: { scored: 48, max: 50, weightage: 15 },
      cat2: { scored: 49, max: 50, weightage: 15 },
      da1: { scored: 10, max: 10, weightage: 10 },
      da2: { scored: 10, max: 10, weightage: 10 },
      quiz: { scored: 10, max: 10, weightage: 10 },
      fatProjected: { minNeededForS: 68, minNeededForA: 50, max: 100 },
    },
  },
  {
    id: "bece302l",
    code: "BECE302L",
    title: "VLSI System Design & CMOS Circuits",
    type: "Theory",
    slot: "F1 + TF1",
    venue: "AB-1 • Room 202",
    room: { roomNumber: "202", blockName: "Academic Block 1", fullVenue: "AB-1 • Room 202" },
    faculty: "Dr. Manikandan P",
    credits: 4,
    attendance: calculateAttendance(20, 23),
    marks: {
      cat1: { scored: 43, max: 50, weightage: 15 },
      cat2: { scored: 45, max: 50, weightage: 15 },
      da1: { scored: 9.5, max: 10, weightage: 10 },
      da2: { scored: 10, max: 10, weightage: 10 },
      quiz: { scored: 9, max: 10, weightage: 10 },
      fatProjected: { minNeededForS: 76, minNeededForA: 62, max: 100 },
    },
  },
  {
    id: "bece355p",
    code: "BECE355P",
    title: "Cloud Computing & Networks Lab",
    type: "Lab",
    slot: "L15 + L16",
    venue: "SJT • Lab 318",
    room: { roomNumber: "Lab 318", blockName: "Silver Jubilee Tower", fullVenue: "SJT • Lab 318" },
    faculty: "Dr. Prabhakar V",
    credits: 1.5,
    attendance: calculateAttendance(13, 14),
  },
];

export const mockTimetable: TimetableSlot[] = [
  // MONDAY
  {
    id: "mon-1",
    day: "MON",
    subject: "VLSI System Design & CMOS Circuits",
    subjectCode: "BECE302L",
    courseCode: "BECE302L",
    courseTitle: "VLSI System Design & CMOS Circuits",
    startTime: "08:00 AM",
    endTime: "08:50 AM",
    slot: "F1",
    slotName: "F1",
    room: { roomNumber: "202", blockName: "Academic Block 1", fullVenue: "AB-1 • Room 202" },
    venue: "AB-1 • Room 202",
    faculty: "Dr. Manikandan P",
    isLab: false,
    attendance: calculateAttendance(20, 23),
  },
  {
    id: "mon-2",
    day: "MON",
    subject: "Database Systems & Architecture",
    subjectCode: "BCSE302L",
    courseCode: "BCSE302L",
    courseTitle: "Database Systems & Architecture",
    startTime: "09:00 AM",
    endTime: "09:50 AM",
    slot: "A1",
    slotName: "A1",
    room: { roomNumber: "304", blockName: "Academic Block 2", fullVenue: "AB-2 • Room 304" },
    venue: "AB-2 • Room 304",
    faculty: "Dr. Rajesh Varma",
    isLab: false,
    attendance: calculateAttendance(18, 21),
  },
  {
    id: "mon-3",
    day: "MON",
    subject: "Artificial Intelligence & Machine Learning",
    subjectCode: "BECE309L",
    courseCode: "BECE309L",
    courseTitle: "Artificial Intelligence & Machine Learning",
    startTime: "11:00 AM",
    endTime: "11:50 AM",
    slot: "B1",
    slotName: "B1",
    room: { roomNumber: "504", blockName: "Silver Jubilee Tower", fullVenue: "SJT • Room 504" },
    venue: "SJT • Room 504",
    faculty: "Dr. K. S. Ramanujam",
    isLab: false,
    attendance: calculateAttendance(19, 22),
  },
  {
    id: "mon-4",
    day: "MON",
    subject: "Advanced Cloud Computing",
    subjectCode: "BECE355L",
    courseCode: "BECE355L",
    courseTitle: "Advanced Cloud Computing",
    startTime: "02:00 PM",
    endTime: "02:50 PM",
    slot: "C1",
    slotName: "C1",
    room: { roomNumber: "402", blockName: "Academic Block 2", fullVenue: "AB-2 • Room 402" },
    venue: "AB-2 • Room 402",
    faculty: "Dr. Prabhakar V",
    isLab: false,
    attendance: calculateAttendance(17, 20),
  },
  {
    id: "mon-5",
    day: "MON",
    subject: "Cloud Computing & Networks Lab",
    subjectCode: "BECE355P",
    courseCode: "BECE355P",
    courseTitle: "Cloud Computing & Networks Lab",
    startTime: "03:00 PM",
    endTime: "04:40 PM",
    slot: "L15+16",
    slotName: "L15 + L16",
    room: { roomNumber: "Lab 318", blockName: "Silver Jubilee Tower", fullVenue: "SJT • Lab 318" },
    venue: "SJT • Lab 318",
    faculty: "Dr. Prabhakar V",
    isLab: true,
    attendance: calculateAttendance(13, 14),
  },

  // TUESDAY
  {
    id: "tue-1",
    day: "TUE",
    subject: "Computer Networks & Protocols",
    subjectCode: "BCSE308L",
    courseCode: "BCSE308L",
    courseTitle: "Computer Networks & Protocols",
    startTime: "08:00 AM",
    endTime: "08:50 AM",
    slot: "D1",
    slotName: "D1",
    room: { roomNumber: "208", blockName: "Academic Block 3", fullVenue: "AB-3 • Room 208" },
    venue: "AB-3 • Room 208",
    faculty: "Prof. Shalini Roy",
    isLab: false,
    attendance: calculateAttendance(21, 24),
  },
  {
    id: "tue-2",
    day: "TUE",
    subject: "Probability and Statistics",
    subjectCode: "BMAT202L",
    courseCode: "BMAT202L",
    courseTitle: "Probability and Statistics",
    startTime: "10:00 AM",
    endTime: "10:50 AM",
    slot: "E1",
    slotName: "E1",
    room: { roomNumber: "118", blockName: "Main Building", fullVenue: "MB • Room 118" },
    venue: "MB • Room 118",
    faculty: "Dr. Thangaraj M",
    isLab: false,
    attendance: calculateAttendance(20, 22),
  },
  {
    id: "tue-3",
    day: "TUE",
    subject: "AI & Machine Learning (Tutorial)",
    subjectCode: "BECE309L",
    courseCode: "BECE309L",
    courseTitle: "AI & Machine Learning (Tutorial)",
    startTime: "11:00 AM",
    endTime: "11:50 AM",
    slot: "TB1",
    slotName: "TB1",
    room: { roomNumber: "504", blockName: "Silver Jubilee Tower", fullVenue: "SJT • Room 504" },
    venue: "SJT • Room 504",
    faculty: "Dr. K. S. Ramanujam",
    isLab: false,
    attendance: calculateAttendance(19, 22),
  },
  {
    id: "tue-4",
    day: "TUE",
    subject: "Computer Networks Packet Capture Lab",
    subjectCode: "BCSE308L",
    courseCode: "BCSE308L",
    courseTitle: "Computer Networks Packet Capture Lab",
    startTime: "02:00 PM",
    endTime: "03:40 PM",
    slot: "L21+22",
    slotName: "L21 + L22",
    room: { roomNumber: "Lab 512", blockName: "Silver Jubilee Tower", fullVenue: "SJT • Lab 512" },
    venue: "SJT • Lab 512",
    faculty: "Prof. Shalini Roy",
    isLab: true,
    attendance: calculateAttendance(21, 24),
  },

  // WEDNESDAY
  {
    id: "wed-1",
    day: "WED",
    subject: "Database Systems (Tutorial)",
    subjectCode: "BCSE302L",
    courseCode: "BCSE302L",
    courseTitle: "Database Systems (Tutorial)",
    startTime: "08:00 AM",
    endTime: "08:50 AM",
    slot: "TA1",
    slotName: "TA1",
    room: { roomNumber: "304", blockName: "Academic Block 2", fullVenue: "AB-2 • Room 304" },
    venue: "AB-2 • Room 304",
    faculty: "Dr. Rajesh Varma",
    isLab: false,
    attendance: calculateAttendance(18, 21),
  },
  {
    id: "wed-2",
    day: "WED",
    subject: "Database Systems & Architecture",
    subjectCode: "BCSE302L",
    courseCode: "BCSE302L",
    courseTitle: "Database Systems & Architecture",
    startTime: "09:00 AM",
    endTime: "09:50 AM",
    slot: "A1",
    slotName: "A1",
    room: { roomNumber: "304", blockName: "Academic Block 2", fullVenue: "AB-2 • Room 304" },
    venue: "AB-2 • Room 304",
    faculty: "Dr. Rajesh Varma",
    isLab: false,
    attendance: calculateAttendance(18, 21),
  },
  {
    id: "wed-3",
    day: "WED",
    subject: "Advanced Cloud Computing (Tutorial)",
    subjectCode: "BECE355L",
    courseCode: "BECE355L",
    courseTitle: "Advanced Cloud Computing (Tutorial)",
    startTime: "10:00 AM",
    endTime: "10:50 AM",
    slot: "TC1",
    slotName: "TC1",
    room: { roomNumber: "402", blockName: "Academic Block 2", fullVenue: "AB-2 • Room 402" },
    venue: "AB-2 • Room 402",
    faculty: "Dr. Prabhakar V",
    isLab: false,
    attendance: calculateAttendance(17, 20),
  },
  {
    id: "wed-4",
    day: "WED",
    subject: "AI Algorithms Practical Session",
    subjectCode: "BECE309L",
    courseCode: "BECE309L",
    courseTitle: "AI Algorithms Practical Session",
    startTime: "02:00 PM",
    endTime: "03:40 PM",
    slot: "L31+32",
    slotName: "L31 + L32",
    room: { roomNumber: "Lab 402", blockName: "Silver Jubilee Tower", fullVenue: "SJT • Lab 402" },
    venue: "SJT • Lab 402",
    faculty: "Dr. K. S. Ramanujam",
    isLab: true,
    attendance: calculateAttendance(19, 22),
  },

  // THURSDAY
  {
    id: "thu-1",
    day: "THU",
    subject: "VLSI CMOS Design (Tutorial)",
    subjectCode: "BECE302L",
    courseCode: "BECE302L",
    courseTitle: "VLSI CMOS Design (Tutorial)",
    startTime: "08:00 AM",
    endTime: "08:50 AM",
    slot: "TF1",
    slotName: "TF1",
    room: { roomNumber: "202", blockName: "Academic Block 1", fullVenue: "AB-1 • Room 202" },
    venue: "AB-1 • Room 202",
    faculty: "Dr. Manikandan P",
    isLab: false,
    attendance: calculateAttendance(20, 23),
  },
  {
    id: "thu-2",
    day: "THU",
    subject: "Probability and Statistics (Tutorial)",
    subjectCode: "BMAT202L",
    courseCode: "BMAT202L",
    courseTitle: "Probability and Statistics (Tutorial)",
    startTime: "09:00 AM",
    endTime: "09:50 AM",
    slot: "TE1",
    slotName: "TE1",
    room: { roomNumber: "118", blockName: "Main Building", fullVenue: "MB • Room 118" },
    venue: "MB • Room 118",
    faculty: "Dr. Thangaraj M",
    isLab: false,
    attendance: calculateAttendance(20, 22),
  },
  {
    id: "thu-3",
    day: "THU",
    subject: "Probability and Statistics",
    subjectCode: "BMAT202L",
    courseCode: "BMAT202L",
    courseTitle: "Probability and Statistics",
    startTime: "10:00 AM",
    endTime: "10:50 AM",
    slot: "E1",
    slotName: "E1",
    room: { roomNumber: "118", blockName: "Main Building", fullVenue: "MB • Room 118" },
    venue: "MB • Room 118",
    faculty: "Dr. Thangaraj M",
    isLab: false,
    attendance: calculateAttendance(20, 22),
  },
  {
    id: "thu-4",
    day: "THU",
    subject: "Computer Networks (Tutorial)",
    subjectCode: "BCSE308L",
    courseCode: "BCSE308L",
    courseTitle: "Computer Networks (Tutorial)",
    startTime: "11:00 AM",
    endTime: "11:50 AM",
    slot: "TD1",
    slotName: "TD1",
    room: { roomNumber: "208", blockName: "Academic Block 3", fullVenue: "AB-3 • Room 208" },
    venue: "AB-3 • Room 208",
    faculty: "Prof. Shalini Roy",
    isLab: false,
    attendance: calculateAttendance(21, 24),
  },
  {
    id: "thu-5",
    day: "THU",
    subject: "Advanced Cloud Computing",
    subjectCode: "BECE355L",
    courseCode: "BECE355L",
    courseTitle: "Advanced Cloud Computing",
    startTime: "02:00 PM",
    endTime: "02:50 PM",
    slot: "C1",
    slotName: "C1",
    room: { roomNumber: "402", blockName: "Academic Block 2", fullVenue: "AB-2 • Room 402" },
    venue: "AB-2 • Room 402",
    faculty: "Dr. Prabhakar V",
    isLab: false,
    attendance: calculateAttendance(17, 20),
  },

  // FRIDAY
  {
    id: "fri-1",
    day: "FRI",
    subject: "Artificial Intelligence & Machine Learning",
    subjectCode: "BECE309L",
    courseCode: "BECE309L",
    courseTitle: "Artificial Intelligence & Machine Learning",
    startTime: "09:00 AM",
    endTime: "09:50 AM",
    slot: "B1",
    slotName: "B1",
    room: { roomNumber: "504", blockName: "Silver Jubilee Tower", fullVenue: "SJT • Room 504" },
    venue: "SJT • Room 504",
    faculty: "Dr. K. S. Ramanujam",
    isLab: false,
    attendance: calculateAttendance(19, 22),
  },
  {
    id: "fri-2",
    day: "FRI",
    subject: "Computer Networks & Protocols",
    subjectCode: "BCSE308L",
    courseCode: "BCSE308L",
    courseTitle: "Computer Networks & Protocols",
    startTime: "10:00 AM",
    endTime: "10:50 AM",
    slot: "D1",
    slotName: "D1",
    room: { roomNumber: "208", blockName: "Academic Block 3", fullVenue: "AB-3 • Room 208" },
    venue: "AB-3 • Room 208",
    faculty: "Prof. Shalini Roy",
    isLab: false,
    attendance: calculateAttendance(21, 24),
  },
  {
    id: "fri-3",
    day: "FRI",
    subject: "Advanced Cloud Computing",
    subjectCode: "BECE355L",
    courseCode: "BECE355L",
    courseTitle: "Advanced Cloud Computing",
    startTime: "11:00 AM",
    endTime: "11:50 AM",
    slot: "C1",
    slotName: "C1",
    room: { roomNumber: "402", blockName: "Academic Block 2", fullVenue: "AB-2 • Room 402" },
    venue: "AB-2 • Room 402",
    faculty: "Dr. Prabhakar V",
    isLab: false,
    attendance: calculateAttendance(17, 20),
  },
  {
    id: "fri-4",
    day: "FRI",
    subject: "VLSI System Design & CMOS Circuits",
    subjectCode: "BECE302L",
    courseCode: "BECE302L",
    courseTitle: "VLSI System Design & CMOS Circuits",
    startTime: "02:00 PM",
    endTime: "02:50 PM",
    slot: "F1",
    slotName: "F1",
    room: { roomNumber: "202", blockName: "Academic Block 1", fullVenue: "AB-1 • Room 202" },
    venue: "AB-1 • Room 202",
    faculty: "Dr. Manikandan P",
    isLab: false,
    attendance: calculateAttendance(20, 23),
  },

  // SATURDAY
  {
    id: "sat-1",
    day: "SAT",
    subject: "Probability & Statistics Problem Session",
    subjectCode: "BMAT202L",
    courseCode: "BMAT202L",
    courseTitle: "Probability & Statistics Problem Session",
    startTime: "09:00 AM",
    endTime: "09:50 AM",
    slot: "E1",
    slotName: "E1",
    room: { roomNumber: "118", blockName: "Main Building", fullVenue: "MB • Room 118" },
    venue: "MB • Room 118",
    faculty: "Dr. Thangaraj M",
    isLab: false,
    attendance: calculateAttendance(20, 22),
  },
  {
    id: "sat-2",
    day: "SAT",
    subject: "Database Systems & Architecture (Review)",
    subjectCode: "BCSE302L",
    courseCode: "BCSE302L",
    courseTitle: "Database Systems & Architecture (Review)",
    startTime: "10:00 AM",
    endTime: "10:50 AM",
    slot: "A1",
    slotName: "A1",
    room: { roomNumber: "304", blockName: "Academic Block 2", fullVenue: "AB-2 • Room 304" },
    venue: "AB-2 • Room 304",
    faculty: "Dr. Rajesh Varma",
    isLab: false,
    attendance: calculateAttendance(18, 21),
  },
  {
    id: "sat-3",
    day: "SAT",
    subject: "Machine Learning Models Seminar",
    subjectCode: "BECE309L",
    courseCode: "BECE309L",
    courseTitle: "Machine Learning Models Seminar",
    startTime: "11:00 AM",
    endTime: "11:50 AM",
    slot: "B1",
    slotName: "B1",
    room: { roomNumber: "504", blockName: "Silver Jubilee Tower", fullVenue: "SJT • Room 504" },
    venue: "SJT • Room 504",
    faculty: "Dr. K. S. Ramanujam",
    isLab: false,
    attendance: calculateAttendance(19, 22),
  },
];

export const mockAssignments: Assignment[] = [
  {
    id: "asg-1",
    title: "BECE355L Digital Assignment 1: Docker Microservices & AWS ECS",
    courseCode: "BECE355L",
    courseTitle: "Advanced Cloud Computing",
    faculty: "Dr. Prabhakar V",
    source: "LMS",
    platformName: "VIT Moodle LMS Portal",
    platformUrl: "https://lms.vit.ac.in",
    dueDate: "2026-08-25",
    dueTime: "11:59 PM",
    status: "Pending",
    priority: "Critical",
    weightage: 10,
    instructions: "Submit PDF documentation with ECS cluster architecture and Dockerfile configuration.",
  },
  {
    id: "asg-2",
    title: "BCSE308L Experiment 4: Simulate & Analyze Link Failure on NetSim / CPT",
    courseCode: "BCSE308L",
    courseTitle: "Computer Networks & Protocols",
    faculty: "Prof. Shalini Roy",
    source: "Teams",
    platformName: "Microsoft Teams Class Team",
    platformUrl: "https://teams.microsoft.com",
    dueDate: "2026-08-22",
    dueTime: "05:00 PM",
    status: "Pending",
    priority: "Critical",
    weightage: 5,
    instructions: "Upload network topology .pkt file and throughput drop analysis document.",
  },
  {
    id: "asg-3",
    title: "BECE309L Module 2: NLTK Tokenization & Feature Engineering",
    courseCode: "BECE309L",
    courseTitle: "Artificial Intelligence & Machine Learning",
    faculty: "Dr. K. S. Ramanujam",
    source: "LMS",
    platformName: "VIT Moodle LMS Portal",
    platformUrl: "https://lms.vit.ac.in",
    dueDate: "2026-08-28",
    dueTime: "11:59 PM",
    status: "Pending",
    priority: "Medium",
    weightage: 10,
    instructions: "Submit executable Jupyter notebook with tokenization pipeline on text dataset.",
  },
];

export const mockFees: FeeItem[] = [
  {
    id: "fee-1",
    title: "Tuition Fee - Academic Year 2024-25 (Semester 5)",
    category: "Tuition",
    semester: "Semester 5",
    totalAmount: 198000,
    amount: 198000,
    paidAmount: 198000,
    pendingAmount: 0,
    status: "Paid",
    receiptNumber: "VT/2026/TUI/1100",
    paymentDate: "2026-01-10",
  },
  {
    id: "fee-2",
    title: "Hostel & Special Mess Fee (Block-Q, 2-Bed AC)",
    category: "Hostel & Mess",
    semester: "Semester 5",
    totalAmount: 145000,
    amount: 145000,
    paidAmount: 145000,
    pendingAmount: 0,
    status: "Paid",
    receiptNumber: "VT/2026/HST/1100",
    paymentDate: "2026-01-12",
  },
  {
    id: "fee-3",
    title: "End Semester FAT Examination & Assessment Fee",
    category: "Exam",
    semester: "Semester 5",
    totalAmount: 3200,
    amount: 3200,
    paidAmount: 0,
    pendingAmount: 3200,
    dueDate: "2026-09-01",
    status: "Pending",
  },
];

export const mockPlacements: PlacementDrive[] = [
  {
    id: "plc-1",
    companyName: "Google",
    role: "Software Development Engineer (SWE-1)",
    ctc: "₹54.0 LPA",
    eligibilityCgpa: 8.5,
    isEligible: true,
    deadlineToApply: "Aug 28, 2026",
    deadline: "Aug 28, 2026",
    driveDate: "Sep 12, 2026",
    location: "Bangalore / Hyderabad",
    status: "Open",
    tags: ["Super Dream", "Tier-1 Product"],
  },
  {
    id: "plc-2",
    companyName: "Microsoft",
    role: "Software Engineer - Azure Core",
    ctc: "₹48.0 LPA",
    eligibilityCgpa: 8.0,
    isEligible: true,
    deadlineToApply: "Sep 02, 2026",
    deadline: "Sep 02, 2026",
    driveDate: "Sep 18, 2026",
    location: "Noida / Bangalore",
    status: "Open",
    tags: ["Super Dream", "Cloud Infra"],
  },
  {
    id: "plc-3",
    companyName: "Amazon",
    role: "SDE-1 (AWS Distributed Storage)",
    ctc: "₹44.0 LPA",
    eligibilityCgpa: 7.5,
    isEligible: true,
    deadlineToApply: "Aug 24, 2026",
    deadline: "Aug 24, 2026",
    driveDate: "Sep 28, 2026",
    location: "Chennai / Bangalore",
    status: "Applied",
    tags: ["Super Dream"],
  },
];

export const mockDSATopics: DSACategory[] = [
  { name: "Dynamic Programming", solved: 48, total: 60, easy: 15, medium: 24, hard: 9 },
  { name: "Trees & Binary Search Trees", solved: 36, total: 40, easy: 12, medium: 18, hard: 6 },
  { name: "Graphs (BFS, DFS, Dijkstra, Topo)", solved: 31, total: 45, easy: 8, medium: 16, hard: 7 },
  { name: "Sliding Window & Two Pointers", solved: 28, total: 30, easy: 14, medium: 12, hard: 2 },
  { name: "Tries & String Hashing", solved: 18, total: 25, easy: 5, medium: 10, hard: 3 },
];

export const mockAITasks: AIStudyTask[] = [
  {
    id: "ai-1",
    courseCode: "BECE355L",
    courseTitle: "Advanced Cloud Computing",
    type: "Assignment Crunch",
    urgency: "HIGH",
    headline: "AWS Docker & ECS Microservices DA Due in 3 Days (VIT LMS)",
    reason: "Internal weightage is 10%. Submit cluster architecture and Dockerfile.",
    estimatedHours: 2.0,
    suggestedSlot: "Tonight 08:30 PM - 10:30 PM",
  },
  {
    id: "ai-2",
    courseCode: "BCSE308L",
    courseTitle: "Computer Networks & Protocols",
    type: "Lab Submission",
    urgency: "HIGH",
    headline: "Expt 4 NetSim Link Failure Simulation Due on MS Teams",
    reason: "Verify packet trace loss metrics and prepare report before Friday submission.",
    estimatedHours: 1.5,
    suggestedSlot: "Thursday 04:00 PM - 05:30 PM",
  },
];
