"""
Shared table-parsing primitives for VTOP pages.

VTOP's HTML is generated by an old JSF-style stack and has two habits that make
naive parsing wrong:

1. **Column order is not stable.** Every module must locate its columns by
   reading the header text, never by hardcoding positions. VTOP adds and removes
   columns (a leading "Invoice" column on the course list, a grouped "Credits"
   header spanning two cells) between semesters and campuses.

2. **Header cells are sometimes ``<th>`` and sometimes ``<td>``.** This matters
   because we flatten each table into a single list of ``<td>`` elements and walk
   it with a stride. If the header used ``<td>``, its cells are *in* that list
   and every index must be shifted one row forward.

``discover_columns`` handles (1); ``header_layout`` handles (2).
"""

from __future__ import annotations

from typing import Callable, Dict, List, Optional, Sequence, Tuple

from bs4 import BeautifulSoup
from bs4.element import Tag

# A rule maps a logical column name to a predicate over the lowercased,
# whitespace-collapsed header text.
ColumnRule = Tuple[str, Callable[[str], bool]]


def raw_text(node: Tag) -> str:
    """
    Equivalent of the DOM ``innerText`` that the reference implementation reads.

    Because the reference parses into a document that is never rendered,
    ``innerText`` degrades to ``textContent``: tabs and newlines are preserved.
    Several VTOP cells rely on that (values separated by ``<br>``), so we must
    NOT collapse whitespace here. Callers apply their own cleanup.
    """
    return node.get_text()


def norm(text: str) -> str:
    """Lowercase and collapse all whitespace runs to single spaces."""
    return " ".join(text.split()).lower()


def exactly(value: str) -> Callable[[str], bool]:
    """Rule predicate: header equals ``value`` after normalisation."""
    return lambda text: text == value


def contains(*needles: str) -> Callable[[str], bool]:
    """Rule predicate: header contains every one of ``needles``."""
    return lambda text: all(needle in text for needle in needles)


def discover_columns(
    headings: Sequence[Tag], rules: Sequence[ColumnRule]
) -> Dict[str, int]:
    """
    Map logical column names to indices by matching header text against rules.

    Semantics deliberately mirror the reference implementation's if/else-if
    chain: for a given heading the *first* matching rule wins, and a later
    heading matching the same rule overwrites the earlier index. Rule order is
    therefore load-bearing — see the per-module comments before reordering.
    """
    found: Dict[str, int] = {}
    for index, heading in enumerate(headings):
        text = norm(raw_text(heading))
        for name, predicate in rules:
            if predicate(text):
                found[name] = index
                break
    return found


def header_layout(table: Tag) -> Tuple[List[Tag], int, int]:
    """
    Return ``(header_cells, index_offset, stride)`` for a table.

    ``index_offset`` is what must be added to every discovered column index so
    it addresses the first *data* row within ``table.find_all("td")``:

    * header uses ``<th>``  -> offset 0    (header cells absent from the td list)
    * header uses ``<td>``  -> offset N    (skip the header row)

    ``stride`` is how far to advance each index to reach the next row.
    """
    header_cells = table.find_all("th")
    if header_cells:
        return header_cells, 0, len(header_cells)

    first_row = table.find("tr")
    if first_row is None:
        return [], 0, 0

    header_cells = first_row.find_all("td")
    return header_cells, len(header_cells), len(header_cells)


def walk_rows(
    cells: Sequence[Tag],
    columns: Dict[str, int],
    required: Sequence[str],
    stride: int,
    offset: int = 0,
) -> List[Dict[str, Tag]]:
    """
    Walk a flattened cell list row by row, yielding one dict of Tags per row.

    Stops as soon as any required column would read past the end of the list —
    matching the reference implementation's ``while (all indices < length)``
    guard, which is what stops it walking into footer rows.
    """
    if stride <= 0 or not required:
        return []
    if any(name not in columns for name in required):
        return []

    cursor = {name: index + offset for name, index in columns.items()}
    rows: List[Dict[str, Tag]] = []
    total = len(cells)

    while all(cursor[name] < total for name in required):
        row: Dict[str, Tag] = {}
        for name, index in cursor.items():
            if 0 <= index < total:
                row[name] = cells[index]
        rows.append(row)
        for name in cursor:
            cursor[name] += stride

    return rows


# -- scalar coercion --------------------------------------------------------
# These deliberately return None rather than a placeholder. A missing value must
# stay missing all the way to the UI so it can be rendered as "not available"
# instead of a number the student might act on.


def to_int(node: Optional[Tag]) -> Optional[int]:
    if node is None:
        return None
    text = raw_text(node).strip()
    if not text:
        return None
    match = _leading_number(text)
    if match is None:
        return None
    try:
        return int(float(match))
    except ValueError:
        return None


def to_float(node: Optional[Tag]) -> Optional[float]:
    if node is None:
        return None
    text = raw_text(node).strip()
    if not text:
        return None
    match = _leading_number(text)
    if match is None:
        return None
    try:
        return float(match)
    except ValueError:
        return None


def to_text(node: Optional[Tag]) -> Optional[str]:
    """Trimmed cell text, or None when empty or a hyphen-only placeholder."""
    if node is None:
        return None
    text = " ".join(raw_text(node).split()).strip()
    if not text:
        return None
    # VTOP writes "-" or "--" for "not assigned yet".
    if not text.replace("-", "").strip():
        return None
    return text


def _leading_number(text: str) -> Optional[str]:
    """
    Extract a leading numeric token, the way JS ``parseFloat`` would.

    ``parseFloat("18 / 20")`` is 18, and ``parseFloat("abc")`` is NaN. We keep
    that behaviour so counts like "18" inside "18 of 20" parse identically to
    the reference client.
    """
    stripped = text.strip()
    out: List[str] = []
    seen_dot = False
    for i, ch in enumerate(stripped):
        if ch.isdigit():
            out.append(ch)
        elif ch in "+-" and i == 0:
            out.append(ch)
        elif ch == "." and not seen_dot and out:
            seen_dot = True
            out.append(ch)
        else:
            break
    candidate = "".join(out).rstrip(".")
    if not candidate or candidate in "+-":
        return None
    return candidate


def soup_of(html: str) -> BeautifulSoup:
    return BeautifulSoup(html, "html.parser")


def body_says(html: str, *phrases: str) -> bool:
    """True when the raw response contains any of ``phrases`` (case-insensitive)."""
    lowered = html.lower()
    return any(phrase in lowered for phrase in phrases)
