import { StudentProfile, Course, TimetableSlot, Assignment, FeeItem, PlacementDrive, DSACategory, AIStudyTask } from '../types';
import { calculateAttendance } from './attendanceEngine';

export const mockStudentProfile: StudentProfile = {
  name: "Pragyan Jain",
  regNo: "22BCE10429",
  email: "pragyan.jain2022@vitstudent.ac.in",
  program: "B.Tech - Computer Science and Engineering",
  branch: "Computer Science & Engineering",
  semester: 4,
  batch: "2022 - 2026",
  cgpa: 8.72,
  creditsEarned: 68,
  totalCreditsRequired: 160,
  rank: 14,
  lastSynced: "Just now (VTOP API Live)",
  overallAttendance: calculateAttendance(102, 118), // 86.4%
};

export const mockCourses: Course[] = [
  {
    id: "cse2004",
    code: "CSE2004",
    title: "Database Management Systems",
    type: "Theory",
    slot: "A1 + TA1",
    venue: "AB-2 • Room 304",
    faculty: "Dr. K. S. Ramanujam",
    credits: 4,
    attendance: calculateAttendance(18, 21), // 85.7%, Safe to miss: 3
    marks: {
      cat1: { scored: 44, max: 50, weightage: 15 },
      cat2: { scored: 46, max: 50, weightage: 15 },
      da1: { scored: 10, max: 10, weightage: 10 },
      da2: { scored: 9.5, max: 10, weightage: 10 },
      quiz: { scored: 10, max: 10, weightage: 10 },
      fatProjected: { minNeededForS: 78, minNeededForA: 64, max: 100 },
    },
    gradeHistory: [
      { sem: 1, grade: "S", credits: 21 },
      { sem: 2, grade: "A", credits: 23 },
      { sem: 3, grade: "A", credits: 24 },
    ]
  },
  {
    id: "cse2005",
    code: "CSE2005",
    title: "Design & Analysis of Algorithms",
    type: "Embedded",
    slot: "B1 + TB1 + L31+L32",
    venue: "AB-3 • Room 205",
    faculty: "Prof. Ananya Sen",
    credits: 4,
    attendance: calculateAttendance(16, 20), // 80.0%, Safe to miss: 1
    marks: {
      cat1: { scored: 42, max: 50, weightage: 15 },
      cat2: { scored: 41, max: 50, weightage: 15 },
      da1: { scored: 9, max: 10, weightage: 10 },
      da2: { scored: 10, max: 10, weightage: 10 },
      quiz: { scored: 8.5, max: 10, weightage: 10 },
      fatProjected: { minNeededForS: 82, minNeededForA: 68, max: 100 },
    }
  },
  {
    id: "cse3002",
    code: "CSE3002",
    title: "Cloud Computing & Distributed Systems",
    type: "Theory",
    slot: "C1 + TC1",
    venue: "TT • Room 412",
    faculty: "Dr. Rajesh Varma",
    credits: 3,
    attendance: calculateAttendance(14, 20), // 70.0% -> Below 75%! Need to attend 4 classes
    marks: {
      cat1: { scored: 35, max: 50, weightage: 15 },
      cat2: { scored: 38, max: 50, weightage: 15 },
      da1: { scored: 8, max: 10, weightage: 10 },
      da2: { scored: 8.5, max: 10, weightage: 10 },
      quiz: { scored: 9, max: 10, weightage: 10 },
      fatProjected: { minNeededForS: 88, minNeededForA: 72, max: 100 },
    }
  },
  {
    id: "cse2003",
    code: "CSE2003",
    title: "Computer Networks & Protocols",
    type: "Theory",
    slot: "D1 + TD1",
    venue: "SJT • Room 502",
    faculty: "Prof. Shalini Roy",
    credits: 3,
    attendance: calculateAttendance(22, 24), // 91.7%, Safe to miss: 5
    marks: {
      cat1: { scored: 48, max: 50, weightage: 15 },
      cat2: { scored: 47, max: 50, weightage: 15 },
      da1: { scored: 10, max: 10, weightage: 10 },
      da2: { scored: 10, max: 10, weightage: 10 },
      quiz: { scored: 10, max: 10, weightage: 10 },
      fatProjected: { minNeededForS: 70, minNeededForA: 55, max: 100 },
    }
  },
  {
    id: "mat2001",
    code: "MAT2001",
    title: "Linear Algebra and Complex Variables",
    type: "Theory",
    slot: "E1 + TE1",
    venue: "MB • Room 118",
    faculty: "Dr. P. Venkatesan",
    credits: 4,
    attendance: calculateAttendance(19, 21), // 90.5%, Safe to miss: 4
    marks: {
      cat1: { scored: 40, max: 50, weightage: 15 },
      cat2: { scored: 43, max: 50, weightage: 15 },
      da1: { scored: 9, max: 10, weightage: 10 },
      da2: { scored: 9, max: 10, weightage: 10 },
      quiz: { scored: 8, max: 10, weightage: 10 },
      fatProjected: { minNeededForS: 84, minNeededForA: 70, max: 100 },
    }
  },
  {
    id: "cse2004-lab",
    code: "CSE2004L",
    title: "DBMS Laboratory (PostgreSQL & NoSQL)",
    type: "Lab",
    slot: "L15 + L16",
    venue: "SJT • Lab 318",
    faculty: "Dr. K. S. Ramanujam",
    credits: 1.5,
    attendance: calculateAttendance(13, 14), // 92.8%
  }
];

export const mockTimetable: TimetableSlot[] = [
  // MONDAY
  {
    id: "mon-1",
    day: "MON",
    courseCode: "CSE2004",
    courseTitle: "Database Management Systems",
    startTime: "09:00 AM",
    endTime: "09:50 AM",
    slotName: "A1",
    venue: "AB-2 • Room 304",
    faculty: "Dr. K. S. Ramanujam",
    isLab: false,
    attendance: calculateAttendance(18, 21), // Safe to miss: 3
  },
  {
    id: "mon-2",
    day: "MON",
    courseCode: "CSE2005",
    courseTitle: "Design & Analysis of Algorithms",
    startTime: "11:00 AM",
    endTime: "11:50 AM",
    slotName: "B1",
    venue: "AB-3 • Room 205",
    faculty: "Prof. Ananya Sen",
    isLab: false,
    attendance: calculateAttendance(16, 20), // Safe to miss: 1
  },
  {
    id: "mon-3",
    day: "MON",
    courseCode: "CSE3002",
    courseTitle: "Cloud Computing & Distributed Systems",
    startTime: "02:00 PM",
    endTime: "02:50 PM",
    slotName: "C1",
    venue: "TT • Room 412",
    faculty: "Dr. Rajesh Varma",
    isLab: false,
    attendance: calculateAttendance(14, 20), // 70%, ⚠ Attend next 4 classes
  },

  // TUESDAY
  {
    id: "tue-1",
    day: "TUE",
    courseCode: "CSE2003",
    courseTitle: "Computer Networks & Protocols",
    startTime: "08:00 AM",
    endTime: "08:50 AM",
    slotName: "D1",
    venue: "SJT • Room 502",
    faculty: "Prof. Shalini Roy",
    isLab: false,
    attendance: calculateAttendance(22, 24),
  },
  {
    id: "tue-2",
    day: "TUE",
    courseCode: "MAT2001",
    courseTitle: "Linear Algebra and Complex Variables",
    startTime: "10:00 AM",
    endTime: "10:50 AM",
    slotName: "E1",
    venue: "MB • Room 118",
    faculty: "Dr. P. Venkatesan",
    isLab: false,
    attendance: calculateAttendance(19, 21),
  },
  {
    id: "tue-3",
    day: "TUE",
    courseCode: "CSE2004L",
    courseTitle: "DBMS Laboratory (PostgreSQL & NoSQL)",
    startTime: "02:00 PM",
    endTime: "03:40 PM",
    slotName: "L15 + L16",
    venue: "SJT • Lab 318",
    faculty: "Dr. K. S. Ramanujam",
    isLab: true,
    attendance: calculateAttendance(13, 14),
  },

  // WEDNESDAY
  {
    id: "wed-1",
    day: "WED",
    courseCode: "CSE2004",
    courseTitle: "Database Management Systems",
    startTime: "09:00 AM",
    endTime: "09:50 AM",
    slotName: "TA1",
    venue: "AB-2 • Room 304",
    faculty: "Dr. K. S. Ramanujam",
    isLab: false,
    attendance: calculateAttendance(18, 21),
  },
  {
    id: "wed-2",
    day: "WED",
    courseCode: "CSE3002",
    courseTitle: "Cloud Computing & Distributed Systems",
    startTime: "10:00 AM",
    endTime: "10:50 AM",
    slotName: "TC1",
    venue: "TT • Room 412",
    faculty: "Dr. Rajesh Varma",
    isLab: false,
    attendance: calculateAttendance(14, 20),
  },
  {
    id: "wed-3",
    day: "WED",
    courseCode: "CSE2005",
    courseTitle: "DAA Lab Session (Dynamic Programming & Graphs)",
    startTime: "02:00 PM",
    endTime: "03:40 PM",
    slotName: "L31 + L32",
    venue: "AB-3 • Lab 102",
    faculty: "Prof. Ananya Sen",
    isLab: true,
    attendance: calculateAttendance(16, 20),
  },

  // THURSDAY
  {
    id: "thu-1",
    day: "THU",
    courseCode: "MAT2001",
    courseTitle: "Linear Algebra and Complex Variables",
    startTime: "09:00 AM",
    endTime: "09:50 AM",
    slotName: "TE1",
    venue: "MB • Room 118",
    faculty: "Dr. P. Venkatesan",
    isLab: false,
    attendance: calculateAttendance(19, 21),
  },
  {
    id: "thu-2",
    day: "THU",
    courseCode: "CSE2003",
    courseTitle: "Computer Networks & Protocols",
    startTime: "11:00 AM",
    endTime: "11:50 AM",
    slotName: "TD1",
    venue: "SJT • Room 502",
    faculty: "Prof. Shalini Roy",
    isLab: false,
    attendance: calculateAttendance(22, 24),
  },

  // FRIDAY
  {
    id: "fri-1",
    day: "FRI",
    courseCode: "CSE2005",
    courseTitle: "Design & Analysis of Algorithms",
    startTime: "09:00 AM",
    endTime: "09:50 AM",
    slotName: "TB1",
    venue: "AB-3 • Room 205",
    faculty: "Prof. Ananya Sen",
    isLab: false,
    attendance: calculateAttendance(16, 20),
  },
  {
    id: "fri-2",
    day: "FRI",
    courseCode: "CSE3002",
    courseTitle: "Cloud Computing & Distributed Systems",
    startTime: "11:00 AM",
    endTime: "11:50 AM",
    slotName: "C1",
    venue: "TT • Room 412",
    faculty: "Dr. Rajesh Varma",
    isLab: false,
    attendance: calculateAttendance(14, 20),
  },

  // SATURDAY
  {
    id: "sat-1",
    day: "SAT",
    courseCode: "CSE2004",
    courseTitle: "Database Management Systems (Tutorial)",
    startTime: "10:00 AM",
    endTime: "10:50 AM",
    slotName: "A1",
    venue: "AB-2 • Room 304",
    faculty: "Dr. K. S. Ramanujam",
    isLab: false,
    attendance: calculateAttendance(18, 21),
  }
];

export const mockAssignments: Assignment[] = [
  {
    id: "asg-1",
    title: "Assignment 2: ACID Properties & Concurrency Control",
    courseCode: "CSE2004",
    courseTitle: "Database Management Systems",
    source: "LMS",
    dueDate: "2026-08-19",
    dueTime: "11:59 PM",
    status: "Pending",
    priority: "Critical",
    weightagePercentage: 10,
  },
  {
    id: "asg-2",
    title: "Lab Task 5: Dynamic Programming on Trees & Bitmask",
    courseCode: "CSE2005",
    courseTitle: "Design & Analysis of Algorithms",
    source: "Teams",
    dueDate: "2026-08-21",
    dueTime: "05:00 PM",
    status: "Pending",
    priority: "Medium",
    weightagePercentage: 5,
  },
  {
    id: "asg-3",
    title: "Docker Containerization & Kubernetes Cluster Setup",
    courseCode: "CSE3002",
    courseTitle: "Cloud Computing & Distributed Systems",
    source: "LMS",
    dueDate: "2026-08-25",
    dueTime: "11:59 PM",
    status: "Pending",
    priority: "Medium",
    weightagePercentage: 10,
  },
  {
    id: "asg-4",
    title: "Wireshark Packet Analysis on TCP 3-Way Handshake",
    courseCode: "CSE2003",
    courseTitle: "Computer Networks & Protocols",
    source: "Teams",
    dueDate: "2026-08-14",
    dueTime: "11:59 PM",
    status: "Submitted",
    priority: "Low",
    weightagePercentage: 5,
  }
];

export const mockFees: FeeItem[] = [
  {
    id: "fee-1",
    title: "Tuition Fee - Academic Year 2024-25 (Sem 4)",
    category: "Tuition",
    semester: "Semester 4",
    totalAmount: 198000,
    paidAmount: 198000,
    pendingAmount: 0,
    dueDate: "2026-01-15",
    status: "Paid",
    receiptNumber: "VT/2026/TUI/94821",
    paymentDate: "2026-01-10",
  },
  {
    id: "fee-2",
    title: "Hostel & Special Mess Fee (Block-Q, 2-Bed AC)",
    category: "Hostel & Mess",
    semester: "Semester 4",
    totalAmount: 145000,
    paidAmount: 145000,
    pendingAmount: 0,
    dueDate: "2026-01-15",
    status: "Paid",
    receiptNumber: "VT/2026/HST/33019",
    paymentDate: "2026-01-12",
  },
  {
    id: "fee-3",
    title: "End Semester FAT Examination & Lab Assessment Fee",
    category: "Exam & Library",
    semester: "Semester 4",
    totalAmount: 3200,
    paidAmount: 0,
    pendingAmount: 3200,
    dueDate: "2026-09-01",
    status: "Pending",
  }
];

export const mockPlacements: PlacementDrive[] = [
  {
    id: "plc-1",
    companyName: "Google",
    logo: "https://upload.wikimedia.org/wikipedia/commons/2/2f/Google_2015_logo.svg",
    role: "Software Engineering Intern (Summer 2025)",
    ctc: "48.5 LPA (equivalent)",
    location: "Bangalore / Hyderabad",
    minCgpa: 8.0,
    eligible: true,
    deadline: "2026-08-30",
    driveDate: "2026-09-12",
    status: "Shortlisted",
    tags: ["Super Dream", "On-Campus", "Tier-1"]
  },
  {
    id: "plc-2",
    companyName: "Microsoft",
    logo: "https://upload.wikimedia.org/wikipedia/commons/9/96/Microsoft_logo_%282012%29.svg",
    role: "Software Engineer - Azure Core",
    ctc: "44.0 LPA",
    location: "Noida / Bangalore",
    minCgpa: 8.0,
    eligible: true,
    deadline: "2026-09-05",
    driveDate: "2026-09-18",
    status: "Applied",
    tags: ["Super Dream", "PPO Offered"]
  },
  {
    id: "plc-3",
    companyName: "D. E. Shaw",
    logo: "https://upload.wikimedia.org/wikipedia/commons/6/65/D._E._Shaw_%26_Co._logo.svg",
    role: "Member Technical (FinTech Systems)",
    ctc: "52.0 LPA",
    location: "Hyderabad",
    minCgpa: 8.5,
    eligible: true,
    deadline: "2026-09-10",
    driveDate: "2026-09-24",
    status: "Upcoming",
    tags: ["Super Dream", "Quant / FinTech"]
  },
  {
    id: "plc-4",
    companyName: "Amazon",
    logo: "https://upload.wikimedia.org/wikipedia/commons/a/a9/Amazon_logo.svg",
    role: "SDE-1 (AWS Data Services)",
    ctc: "45.0 LPA",
    location: "Chennai / Bangalore",
    minCgpa: 7.5,
    eligible: true,
    deadline: "2026-09-20",
    driveDate: "2026-10-02",
    status: "Upcoming",
    tags: ["Super Dream"]
  }
];

export const mockDSATopics: DSACategory[] = [
  { name: "Dynamic Programming", solved: 48, total: 60, easy: 15, medium: 24, hard: 9 },
  { name: "Trees & Binary Search Trees", solved: 36, total: 40, easy: 12, medium: 18, hard: 6 },
  { name: "Graphs (BFS, DFS, Dijkstra, MST)", solved: 31, total: 45, easy: 8, medium: 16, hard: 7 },
  { name: "Sliding Window & Two Pointers", solved: 28, total: 30, easy: 14, medium: 12, hard: 2 },
  { name: "Trie & String Hashing", solved: 14, total: 25, easy: 4, medium: 7, hard: 3 },
  { name: "Heaps & Priority Queues", solved: 20, total: 25, easy: 8, medium: 10, hard: 2 },
];

export const mockAITasks: AIStudyTask[] = [
  {
    id: "ai-1",
    subjectCode: "CSE3002",
    subjectTitle: "Cloud Computing & Distributed Systems",
    category: "Attendance Risk",
    urgency: "HIGH",
    headline: "Critical Attendance Recovery: 70.0% (<75%)",
    actionReason: "You need 4 consecutive attendances without misses to safely enter the 75%+ eligibility bracket before FAT exam hall ticket release.",
    estimatedHours: 1.5,
    suggestedSlot: "Next Wednesday 10:00 AM (TC1) & Friday 11:00 AM (C1)",
  },
  {
    id: "ai-2",
    subjectCode: "CSE2004",
    subjectTitle: "Database Management Systems",
    category: "Assignment Crunch",
    urgency: "HIGH",
    headline: "ACID Transactions DA Due in 4 Days",
    actionReason: "Weightage is 10% of internal assessment. Focus on Two-Phase Locking and Serializability proofs.",
    estimatedHours: 2.5,
    suggestedSlot: "Tonight 08:30 PM - 11:00 PM",
  },
  {
    id: "ai-3",
    subjectCode: "CSE2005",
    subjectTitle: "Design & Analysis of Algorithms",
    category: "Exam Preparation",
    urgency: "MEDIUM",
    headline: "Prepare for CAT-2: Graph Algorithms & Dynamic Programming",
    actionReason: "Scoring 45+ out of 50 guarantees your S-grade projection with 8.72+ CGPA maintenance.",
    estimatedHours: 3.0,
    suggestedSlot: "Thursday 04:00 PM - 07:00 PM",
  },
  {
    id: "ai-4",
    subjectCode: "DSA",
    subjectTitle: "Placement Prep: Top 100 Liked",
    category: "DSA Practice",
    urgency: "OPTIMAL",
    headline: "Solve 2 Hard Graph Problems (Tarjan's & Kosaraju's Algorithm)",
    actionReason: "Targeted for upcoming Google / Microsoft online assessments in September.",
    estimatedHours: 2.0,
    suggestedSlot: "Saturday Morning 09:00 AM - 11:00 AM",
  }
];
